### ISSUE TITLE
Help with KDE

### ISSUE THREAD

**Issue by thomasaarholt** [cophus/scanning-drift-corr#1]
I'm not used to working with kernel density estimation, and I think it'd save time if @cophus explains what happens in the [matlab code](https://github.com/cophus/scanning-drift-corr/blob/2ae74ef40d9db247670021623fdf12881606f4c7/matlab/SPmakeImage.m#L50).

There are a few relevant functions:
- [`scipy.stats.gaussian_kde`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html)
- [`scipy.ndimage.gaussian_filter`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html)

I think we should be going straight for the kde function, but I'm unsure how to implement it.

@HamishGBrown I see you've made progress as well! I haven't stuck my code online yet, but I've got a slightly more literal python translation (less efficient) than you have up to the first link in this post. I suggest we both keep going independently and then compare drafts :p

**Comment by thomasaarholt** [comment]
Actually, I got the code to work, but I'm still not convinced that this is anything but a gaussian filter? :)

**Comment by HamishGBrown** [comment]
@thomasaarholt good to hear, still getting my own wee head around KDE. From https://en.wikipedia.org/wiki/Kernel_density_estimation it seems that effectively you are convolving with a Gaussian to estimate the PDF? I'm writing M&M abstracts, posters and talks this week but I'll see if I can find some time this weekend to get my code up to speed.

**Comment by thomasaarholt** [comment]
I've read up a bit now and I see how KDE interpolation and gaussian blur are different but have some similarities.

I wonder if there are faster ways of doing the convolution (like using the `gaussian_kde` function mentioned above), but I keep getting errors due to the zeros present in the padded image.

@cophus 
I'm trying to wrap my head around what exactly this matlab code is doing. I can reproduce it in Python and get two images, one that looks like the original image, and one that has values close to 1. Is the purpose of the latter image for normalisation? Maybe you could explain what you're doing here?

```matlab
% Generate image
sL = sMerge.scanLines(indLines,:,indImage);
sig = reshape(accumarray(indAll(:),[ ...
    w(:,1).*sL(:);
    w(:,2).*sL(:);
    w(:,3).*sL(:);
    w(:,4).*sL(:)],...
    [prod(sMerge.imageSize) 1]),sMerge.imageSize);
count = reshape(accumarray(indAll(:),[ ...
    w(:,1);w(:,2);w(:,3);w(:,4)],...
    [prod(sMerge.imageSize) 1]),sMerge.imageSize);
```

**Comment by cophus** [comment]
So KDE!  For KDE, we can use any kernel, Gaussian or otherwise.  Gaussian has some nice behaviour so I chose it.  

In the above example you pasted, I am computing 2 things - the density of the samples (count), and then density of the signal times the sampling density (sig).  These 2 should always work without issue.  The KDE signal estimate is just:

sig_estimate = sig ./ count

Meaning we divide out the sampling density.  This is actually pretty dangerous since count is zero in many places.  Thus we need to be careful to only divide by count where the sampling density is high enough - we should probably zero sig_estimate everywhere else.

These lines in particular are performing **bilinear resampling**.   Each sample value is dumped into a 2x2 pixel region given by the indsAll vector, with the weights w:

[  (1-dx)*(1-dy)  |  (1-dx) * dy   ]
[    dx * (1-dy)    |       dx * dy    ] 
where dx, dy are the subpixel shifts from the upper left pixel origin).   Note these weights sum to 1.

**Comment by thomasaarholt** [comment]
Thank you for the explanation! Closing as I am happy with it!
